name: Deploy Backend

on:
  push:
    branches:
      - main
    paths:
      - 'backend/lambda/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Zip Lambda code
        working-directory: website/backend/lambda
        run: |
          ls -lrt
          zip visitor-counter1.zip visitor-counter.py

      - name: Deploy Lambda function
        working-directory: website/backend/lambda
        run: |
          ls -lrt
          aws lambda update-function-code \
            --function-name resume-visitor-counter \
            --zip-file fileb://visitor-counter1.zip
