name: Deploy Frontend

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/assets/**'
      - 'frontend/index.html'
      - 'frontend/error.html'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Sync HTML files to S3
        run: |
          aws s3 cp frontend/index.html s3://thanaphat.site/index.html
          aws s3 cp frontend/error.html s3://thanaphat.site/error.html 
      - name: Sync assets to S3
        run: aws s3 sync frontend/assets/ s3://thanaphat.site/assets/ --delete
        
      - name: Invalidate CloudFront cache
        run: |
          aws cloudfront create-invalidation \
            --distribution-id E2T8GLLOK4OXUR \
            --paths "/*"
